---
title: "CUPID-SEQ Fig 2 FINAL"
output: html_notebook
---

The following script includes analysis for validating the CUPID-seq protocol.

Beverly Fu

```{r Standard Setup}
# Configure directories, load libraries and base functions
source(paste0(here::here(), "/0-config.R"))

directory = paste0(here(), "/3-figures/")

output <- setup_tables(paste0(here(), "/1-data/DADA2_BF/"), '/1-data/BF-sample-info.xlsx')
ps <- output$ps # phyloseq object
taxa_order <- output$taxa_order # ASV plot order
samdf <- output$samdf # sample information
samdf$Sample <- rownames(samdf)

total_reads <- as.data.frame(sample_sums(ps)) # get total number of reads
colnames(total_reads) <- "total_reads"
total_reads$Sample <- rownames(total_reads)

# Add read counts
samdf <- samdf %>%
  left_join(total_reads, by = "Sample") %>%
  mutate(total_reads = ifelse(is.na(total_reads), 0, total_reads))

# update samdf of phyloseq
rownames(samdf) <- sub('sample_', '', samdf$Sample) # change row names to be the sequencing name, remove "sample_"
samdf <- samdf %>%
  select(-Sample) 
sample_data(ps) <- sample_data(samdf)

output2 <- setup_tables(paste0(here(), "/1-data/DADA2_HS/"), '/1-data/HS-sample-info.xlsx')
ps2 <- output2$ps # phyloseq object
taxa_order2 <- output2$taxa_order # ASV plot order
samdf2 <- output2$samdf # sample information
samdf2$Sample <- rownames(samdf2)

total_reads <- as.data.frame(sample_sums(ps2)) # get total number of reads
colnames(total_reads) <- "total_reads"
total_reads$Sample <- rownames(total_reads)

# update samdf of phyloseq
samdf2 <- samdf2 %>%
  select(-Sample) 
sample_data(ps2) <- sample_data(samdf2)

cutoff_SI <- 0.001 # Supplementary Info ASV cutoff
cutoff_MT <- 0.01 # Main Text ASV cutoff (to minimize legend)
```

#######################################
# Fig. 2A: Comparison of sequencing platform
#######################################

```{r Fig 2A}

ps2plot <- ps %>% subset_samples(total_reads > 1000)

taxa2keep <- psmelt(ps2plot %>% transform_sample_counts(function(x) x/sum(x))) %>% # convert to relative abundance
  filter(Abundance > cutoff_SI) # identify taxa with relative abundances greater than cutoff

ps2plot <- prune_taxa(taxa2keep$OTU, ps2plot) %>% # keep ASVs in taxa2keep
  transform_sample_counts(function(x) x/sum(x)) # renormalize

df2plot <- psmelt(ps2plot) # convert to long form
df2plot <- set_family_order(df2plot, taxa_order) # set Family2 order

transposed_df <- df2plot %>%
                 group_by(No, Plate, Feature) %>%
                 filter(n() > 1) %>%  # Drop groups with only 1 row
                 mutate(NovaSEQ = ifelse(Platform == "NovaSEQ", ifelse(is.na(Abundance) | Abundance < cutoff_SI, 
                                      -3, log10(Abundance)), NA),
                 MiSEQ = ifelse(Platform == "MiSEQ", ifelse(is.na(Abundance) | Abundance < cutoff_SI, 
                                      -3, log10(Abundance)), NA)) %>%
                 select(No, Plate, Feature, MiSEQ, NovaSEQ) %>%
                 summarise(
                      MiSEQ = pmax(max(MiSEQ, na.rm = TRUE), -3),
                      NovaSEQ = pmax(max(NovaSEQ, na.rm = TRUE), -3),
                      .groups = "drop"
                 )

transposed_df <- merge(transposed_df, taxa_order, by = "Feature")

correlation_result <- transposed_df %>% 
  filter(Feature == "feature_0002") %>%
  summarize(
    cor_value = cor(MiSEQ, NovaSEQ, method = "pearson"),  # Pearson correlation coefficient
    p_value = cor.test(MiSEQ, NovaSEQ, method = "pearson")$p.value,  # Extract p-value
    .groups = "drop")

correlation_result

g <- ggplot(transposed_df %>% filter(Feature == "feature_0002"), aes(x = MiSEQ, y = NovaSEQ)) +
     geom_point(shape = 16, size = 1, color = "#CCCCCC", stroke = 0.2, alpha = 0.5) +  # Fill color for the points
     geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "red", linewidth = 0.3) +  # Add y = x line
     annotate(
        "text",
        x = -3, y = -0.25,
        label = bquote(italic(r) == .(round(correlation_result$cor_value, 2)) ~ "," ~ italic(p) == .(sprintf("%.2e", correlation_result$p_value))),
        color = "red", size = 2, hjust = 0
     ) +
     force_panelsizes(rows =  unit(c(4, 4, 4, 4), "cm"),
                      cols = unit(c(4, 4, 4, 4), "cm"), TRUE) +
     scale_y_continuous(breaks = c(0, -1, -2, -3, -4), limits = c(-3, 0)) + 
     scale_x_continuous(limits = c(-3, 0)) +
     labs(x = "log10(MiSeq rel. abund.)", y = "log10(NovaSeq ASV rel. abund.)") +
     theme_bw() +
     theme(panel.grid.major = element_blank(),      # Remove major grid lines
           panel.grid.minor = element_blank()) +     # Remove minor grid lines
     theme_custom_text() +
     coord_fixed()

ggsave(paste0(directory, "Fig2/Fig2A.pdf"), plot = g, device = "pdf", width = 2, height = 2)


```

#######################################
# Fig. 2B: Comparison of phases
#######################################

```{r Fig 2B}
ps2plot <- ps2 %>% subset_samples(Platform == "NovaSeq"
                              & !Well %in% c("F01", "H01", "H12")) # remove blanks

taxa2keep <- psmelt(ps2plot %>% transform_sample_counts(function(x) x/sum(x))) %>% # convert to relative abundance
  filter(Abundance > cutoff_SI)

ps2plot <- prune_taxa(taxa2keep$OTU, ps2plot) %>%  # keep ASVs in taxa2keep
  transform_sample_counts(function(x) x/sum(x)) # renomalize

df2plot <- psmelt(ps2plot) # convert to long form
df2plot <- set_family_order(df2plot, taxa_order2) # set Family2 order

transposed_df <- df2plot %>%
                 group_by(Subject, Well, Feature) %>%
                 mutate(Phase1 = ifelse(Phase %in% c("L0", "L1"), ifelse(is.na(Abundance) | Abundance < cutoff_SI, 
                                      -3, log10(Abundance)), NA),
                 Phase2 = ifelse(Phase %in% c("L2", "L3"), ifelse(is.na(Abundance) | Abundance < cutoff_SI, 
                                      -3, log10(Abundance)), NA)) %>%
                 select(Subject, Well, Feature, Phase1, Phase2) %>%
                 summarise(
                      Phase1 = pmax(max(Phase1, na.rm = TRUE), -3),
                      Phase2 = pmax(max(Phase2, na.rm = TRUE), -3),
                      .groups = "drop"
                 ) # Drop the grouping after summarization
            
transposed_df <- merge(transposed_df, taxa_order, by = "Feature")

correlation_result <- transposed_df %>%
  filter(Feature == "feature_0002") %>%
  summarize(
    cor_value = cor(Phase1, Phase2, method = "pearson"),  # Pearson correlation coefficient
    p_value = cor.test(Phase1, Phase2, method = "pearson")$p.value,  # Extract p-value
    .groups = "drop")

correlation_result

g <- ggplot(transposed_df %>% filter(Feature == "feature_0002"), aes(x = Phase1, y = Phase2)) +
     geom_point(shape = 16, size = 1, color = "#CCCCCC", stroke = 0.2, alpha = 0.5) +  # Fill color for the points
     geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "red", size = 0.3) +  # Add y = x line
     annotate(
        "text",
        x = -3, y = -0.25,
        label = bquote(italic(r) == .(round(correlation_result$cor_value, 2)) ~ "," ~ italic(p) == .(sprintf("%.2e", correlation_result$p_value))),
        color = "red", size = 2, hjust = 0
     ) +
     force_panelsizes(rows =  unit(c(4, 4, 4, 4), "cm"),
                      cols = unit(c(4, 4, 4, 4), "cm"), TRUE) +
     scale_y_continuous(breaks = c(0, -1, -2, -3, -4), limits = c(-3, 0)) + 
     scale_x_continuous(limits = c(-3, 0)) +
     labs(x = "log10(Phase 1 ASV rel. abund.)", y = "log10(Phase 2 ASV rel. abund.)") +
     theme_bw() +
     theme(panel.grid.major = element_blank(),      # Remove major grid lines
           panel.grid.minor = element_blank()) +     # Remove minor grid lines
     theme_custom_text() +
     coord_fixed()

ggsave(paste0(directory, "Fig2/Fig2B.pdf"), plot = g, device = "pdf", width = 2, height = 2)
```

#######################################
# Fig. 2C: Comparison of pooling
#######################################

```{r Fig 2C}

df2plot <- read.table(paste0(here(), '/1-data/Pool-vs-unpool.txt'), header = TRUE, sep=" ") %>%
   filter(unpooled > 0 & pooled > 0)

correlation_result <- df2plot %>%
  summarize(
    cor_value = cor(log10(unpooled), log10(pooled), method = "pearson"),  # Pearson correlation coefficient
    p_value = cor.test(log10(unpooled), log10(pooled), method = "pearson")$p.value,  # Extract p-value
    .groups = "drop")

correlation_result

g <- ggplot(df2plot, aes(x = log10(unpooled), y = log10(pooled))) +
     geom_point(shape = 16, size = 1, color = "#CCCCCC", stroke = 0.2, alpha = 0.5) +  # Fill color for the points
     geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "red", linewidth = 0.3) +  # Add y = x line
     annotate("text",
        x = -3, y = -0.25,
        label = bquote(italic(r) == .(round(correlation_result$cor_value, 2)) ~ "," ~ italic(p) == .(sprintf("%.2e", correlation_result$p_value))),
        color = "red", size = 2, hjust = 0
     ) +
     force_panelsizes(rows =  unit(c(4, 4, 4, 4), "cm"),
                      cols = unit(c(4, 4, 4, 4), "cm"), TRUE) +
     labs(x = "log10(Unpooled ASV rel. abund.)" , y = "log10(Pooled ASV rel. abund.)") +
     theme_bw() +
     theme(panel.grid.major = element_blank(),      # Remove major grid lines
           panel.grid.minor = element_blank()) +     # Remove minor grid lines
     theme_custom_text() +
     coord_fixed(xlim = c(-3, 0), ylim = c(-3, 0))  # Set limits for both axes

ggsave(paste0(directory, "Fig2/Fig2C.pdf"), plot = g, device = "pdf", width = 2, height = 2)
```